import ctypes
import time

# Generated by Google Gemini



# Windows API Constants
MOUSEEVENTF_LEFTDOWN = 0x0002
MOUSEEVENTF_LEFTUP = 0x0004

def fast_click(iterations):
    # Pre-loading the function into a local variable saves a tiny bit of lookup time
    mouse_event = ctypes.windll.user32.mouse_event
    
    print(f"Starting {iterations} clicks...")
    start_time = time.perf_counter()
    
    for _ in range(iterations):
        # 0, 0, 0, 0 refers to dx, dy, data, and extra_info (not needed for simple clicks)
        mouse_event(MOUSEEVENTF_LEFTDOWN, 0, 0, 0, 0)
        time.sleep(0.005) # 0.005 is ~100 cps
        mouse_event(MOUSEEVENTF_LEFTUP, 0, 0, 0, 0)
    
    end_time = time.perf_counter()
    total_time = end_time - start_time
    print(f"Finished in {total_time:.4f} seconds.")
    print(f"Calculated CPS: {iterations / total_time:.2f}")





if __name__ == "__main__":
    # Give yourself 3 seconds to switch windows
    time.sleep(3)
    fast_click(2000)
